### ISSUE TITLE
Unable to trigger bigexec node consecutively

### ISSUE THREAD

**Issue by nHossainCNG** [Jacques44/node-red-contrib-bigexec#3]
Hello. I'm new to Node Red and came across an issue when using the bigexec node to trigger a batch file. I found that even when the node is done running all of the commands in the batch file, it sort of hangs with a 'running for a few seconds' message visible under the node. Based on the way my flow is set up, I feed the bigexec different arguments each time the flow is triggered. the problem is that the bigexec node just hangs and wont do anything with subsequent triggers (until I re-deploy my flow again).

**Comment by Jacques44** [comment]
Hello,

you seem to be right, there’s an issue since several libraries seem to have involved and my node is not running as requested…

I’m investigating

Regards

**Comment by damajor** [comment]
Issue is still present.

**Comment by Jacques44** [comment]
Hello, do you have a test flow to share?

**Comment by damajor** [comment]
Unfortunately you come 1 year too late, I have switched to an alternative way.

**Comment by ggs67** [comment]
I came across the exact same issue. BigExec stays in "running for a few seconds" state and cannot be triggered again.  I tried to change a number of settings (like using shell node, closing stdin or not) bur nothing helped.

Could you tell me what is your alternative solution ?

**Comment by Jacques44** [comment]
Hello, can you give me a sample flow and/or details on what are you trying to do? inputs, triggers, command, system...

**Comment by Jacques44** [comment]
Usually this is related to the command and tty. If you give me more informations, I'd check

**Comment by Jacques44** [comment]
Hello, solved in 1.3.3.
